USE [master]
GO

/****** Object:  Database [DBTEKNIKSERVIS]    Script Date: 8.07.2021 11:52:49 ******/
CREATE DATABASE [DBTEKNIKSERVIS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBTEKNIKSERVIS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\DBTEKNIKSERVIS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DBTEKNIKSERVIS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS2019\MSSQL\DATA\DBTEKNIKSERVIS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBTEKNIKSERVIS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET  MULTI_USER 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DBTEKNIKSERVIS] SET  READ_WRITE 
GO

