--CREATE PROCEDURE makskategoriurun
--AS
--SELECT TOP 1 TBLKATEGORI.ADI FROM TBLURUN 
--INNER JOIN TBLKATEGORI ON TBLKATEGORI.ID=TBLURUN.KATEGORI
--GROUP BY TBLKATEGORI.ADI ORDER BY COUNT(*) DESC

exec makskategoriurun